---
- hosts: all
  become: yes

  tasks:
    - name: Install Docker
      yum: name=docker state=present update_cache=true
    - name: Start Docker
      service: name=docker state=started



      
    - name: Build a docker image
      command: docker build -t web /home/ec2-user
      
    - name: Remove a container
      command: docker container rm -f mynewapp

       
    - name: Run a container
      command: docker container run -d -p 80:80 --name mynewapp web
       
       
